type arr is array[10] integer

var n: integer is 3;

for i in 1..n loop
  var tempInput:integer is input(integer)
  arr[i] :=  tempInput
end


for i in 1..n - 1 loop
    for j in 1..n - i - 1 loop
        if arr[j] > arr[j + 1] then
            var temp: integer is arr[j];
            arr[j] := arr[j + 1];
            arr[j + 1] := temp;
        end;
    end
end

//use 1 var or 2 var

//1 var
for i in 1..n loop
  writes(arr[i]);
end