type Coordinates is record
    var latitude: real;
    var longitude: real;
end
type Address is record
    var location: Coordinates;
end
var home_address: Address;
home_address.location.latitude := 35.0000;
home_address.location.longitude := -95.0000;

//to test
writeln(home_address.location.latitude) // shoud output 35.0 (logically)

home_address.location.longitude := 56.32;
writeln(home_address.location.longitude) //56.32?

